#!/bin/bash

THE_PWD=`pwd`

BUILDSCRIPT_LOCATION=${3:-~/Containers/container-vim-yavin}
VIM_USER=${1:-vim}
CONTAINER_NAME=${2:-vim-yavin}

cd $BUILDSCRIPT_LOCATION

docker build -t ${CONTAINER_NAME} \
  --squash \
  --build-arg VIMUSER=${VIM_USER} \
  .

vpwd='-v `pwd`:`pwd`'
wpwd='-w `pwd`'

runcommand="`cat <<EOF
#!/bin/bash
${CONTAINER_NAME}() {
  docker run -it --rm \
    ${vpwd} $wpwd \
    -h ${CONTAINER_NAME}.local \
    ${CONTAINER_NAME}
}
EOF`"

cd $THE_PWD
echo "$runcommand" > ~/bin/containers.d/${CONTAINER_NAME}
cat <<EOF

  Reload your ~/.bash_profile to alias the container command ${CONTAINER_NAME}()

EOF

